import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { createClient } from '@/utils/supabase/server';
import { logActivity } from '@/lib/activity-logger';

function extractCodes(raw: unknown): { qrCode?: string; batchCode?: string } {
  if (typeof raw !== 'string') return {};
  const trimmed = raw.trim();
  if (!trimmed) return {};

  // If the scanner returns the JSON payload generated by the field-agent QR page,
  // parse it and extract qrCode / batchCode.
  try {
    const parsed = JSON.parse(trimmed);
    if (parsed && typeof parsed === 'object') {
      const qrCode = typeof (parsed as any).qrCode === 'string' ? (parsed as any).qrCode.trim() : undefined;
      const batchCode = typeof (parsed as any).batchCode === 'string' ? (parsed as any).batchCode.trim() : undefined;
      return { qrCode, batchCode };
    }
  } catch {
    // not JSON
  }

  // Fallback: treat as either a qrCode or a batchCode
  return { qrCode: trimmed, batchCode: trimmed };
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const rawInput = body?.qrCode ?? body?.batchCode;
    const { qrCode, batchCode } = extractCodes(rawInput);

    if (!qrCode && !batchCode) {
      return NextResponse.json(
        { error: 'QR code or batch code is required' },
        { status: 400 }
      );
    }

    // Verify user is authenticated and is a warehouse manager
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const profile = await prisma.profile.findUnique({
      where: { userId: user.id },
      select: { role: true, name: true, warehouseId: true }
    });

    if (!profile || profile.role !== 'warehouse_manager') {
      return NextResponse.json(
        { error: 'Insufficient permissions' },
        { status: 403 }
      );
    }

    if (!profile.warehouseId) {
      return NextResponse.json(
        { error: 'No warehouse assigned' },
        { status: 403 }
      );
    }

    // Find the batch by qrCode (preferred) or by batchCode
    const batch = await prisma.cropBatch.findFirst({
      where: {
        OR: [
          ...(qrCode ? [{ qrCode }] : []),
          ...(batchCode ? [{ batchCode }] : []),
        ],
      },
      include: {
        farm: {
          select: { name: true, location: true }
        },
        transportTasks: {
          orderBy: {
            updatedAt: 'desc'
          },
          take: 1,
          include: {
            vehicle: {
              select: { plateNumber: true, type: true }
            },
            driver: {
              select: { name: true, phone: true }
            }
          }
        }
      }
    });

    if (!batch) {
      return NextResponse.json(
        { error: 'Batch not found' },
        { status: 404 }
      );
    }

    // Ensure batch belongs to manager's warehouse
    if (!batch.warehouseId || batch.warehouseId !== profile.warehouseId) {
      return NextResponse.json(
        { error: 'Batch does not belong to your warehouse' },
        { status: 403 }
      );
    }

    // If there is no transport task yet, the coordinator likely hasn't scheduled shipment.
    if (batch.transportTasks.length === 0) {
      return NextResponse.json(
        { error: 'No transport task found for this batch yet. Please ask the transport coordinator to schedule shipment.' },
        { status: 400 }
      );
    }

    // Check if batch is in correct status for receiving.
    // In this app, the coordinator sets SHIPPED when scheduling, so accept SHIPPED.
    // Also accept PACKAGED for older data that hasn't been moved to SHIPPED.
    if (batch.status !== 'SHIPPED' && batch.status !== 'PACKAGED') {
      return NextResponse.json(
        { error: `Batch is in ${batch.status} status. Only SHIPPED (or PACKAGED) batches can be received.` },
        { status: 400 }
      );
    }

    // Log the verification activity
    await logActivity({
      userId: user.id,
      action: 'BATCH_VERIFICATION',
      details: `Verified batch ${batch.batchCode} for receipt at warehouse`,
      entityType: 'CropBatch',
      entityId: batch.id
    });

    const deliveredTask = batch.transportTasks[0];

    // Return a shape that matches components/warehouse-manager/qr-scanner-client.tsx
    return NextResponse.json({
      id: batch.id,
      batchCode: batch.batchCode,
      cropType: batch.cropType,
      quantity: batch.quantity,
      status: batch.status,
      harvestDate: batch.actualHarvest,
      farm: {
        name: batch.farm.name,
        location: batch.farm.location,
      },
      transportTask: deliveredTask ? {
        id: deliveredTask.id,
        driver: {
          name: deliveredTask.driver.name,
          phone: deliveredTask.driver.phone,
        },
        vehicle: {
          plateNumber: deliveredTask.vehicle.plateNumber,
          type: deliveredTask.vehicle.type,
        },
        actualDeliveryDate: deliveredTask.actualDeliveryDate,
      } : undefined,
    });

  } catch (error) {
    console.error('Error verifying batch:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}